package cafeteria;

import configuracionBD.CargarDriver;
import java.awt.BorderLayout;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author manana
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /* -------------- Varibles propias -------------- */
    String urlBD = "jdbc:mysql://localhost/cafetería";
    String usernameBD = "root";
    String passwordBD = "";
    Connection con;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // -------------- CARGANDO DRIVER --------------
        try {
            CargarDriver.cargar("com.mysql.jdbc.Driver");
            System.out.println("Driver Cargado");
        } catch (ClassNotFoundException cne) {
            System.out.println("Driver no cargado"
                    + cne.getMessage());
        }
        // -------------- ESTABLECER CONEXIÓN --------------
        try {
            con = DriverManager.getConnection(urlBD, usernameBD, passwordBD);
        } catch (SQLException sqe) {
            System.out.println("Error siguiente: " + sqe.getMessage());
        }

        /* -------------- Camareros -------------- */
        pintar_camareros();
        /* -------------- Mesas -------------- */
        jB_mesa1.setIcon(setIcono("/img/imgMesa.png", jB_mesa1));
        jB_mesa2.setIcon(setIcono("/img/imgMesa.png", jB_mesa2));
        jB_mesa3.setIcon(setIcono("/img/imgMesa.png", jB_mesa3));
        jB_mesa4.setIcon(setIcono("/img/imgMesa.png", jB_mesa4));
        jB_mesa5.setIcon(setIcono("/img/imgMesa.png", jB_mesa5));
        jB_mesa6.setIcon(setIcono("/img/imgMesa.png", jB_mesa6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jP_camareros = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jP_seleccionar_camareros = new javax.swing.JPanel();
        jP_Mesas = new javax.swing.JPanel();
        jB_mesa1 = new javax.swing.JButton();
        jB_mesa2 = new javax.swing.JButton();
        jB_mesa3 = new javax.swing.JButton();
        jB_mesa4 = new javax.swing.JButton();
        jB_mesa5 = new javax.swing.JButton();
        jB_mesa6 = new javax.swing.JButton();
        jP_Facturacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jP_seleccionar_camarerosLayout = new javax.swing.GroupLayout(jP_seleccionar_camareros);
        jP_seleccionar_camareros.setLayout(jP_seleccionar_camarerosLayout);
        jP_seleccionar_camarerosLayout.setHorizontalGroup(
            jP_seleccionar_camarerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jP_seleccionar_camarerosLayout.setVerticalGroup(
            jP_seleccionar_camarerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jP_seleccionar_camareros);

        javax.swing.GroupLayout jP_camarerosLayout = new javax.swing.GroupLayout(jP_camareros);
        jP_camareros.setLayout(jP_camarerosLayout);
        jP_camarerosLayout.setHorizontalGroup(
            jP_camarerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_camarerosLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jP_camarerosLayout.setVerticalGroup(
            jP_camarerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_camarerosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Camareros", jP_camareros);

        jB_mesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mesa1ActionPerformed(evt);
            }
        });

        jB_mesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mesa2ActionPerformed(evt);
            }
        });

        jB_mesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mesa3ActionPerformed(evt);
            }
        });

        jB_mesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mesa4ActionPerformed(evt);
            }
        });

        jB_mesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mesa5ActionPerformed(evt);
            }
        });

        jB_mesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mesa6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_MesasLayout = new javax.swing.GroupLayout(jP_Mesas);
        jP_Mesas.setLayout(jP_MesasLayout);
        jP_MesasLayout.setHorizontalGroup(
            jP_MesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_MesasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jP_MesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_MesasLayout.createSequentialGroup()
                        .addComponent(jB_mesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jB_mesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jB_mesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_MesasLayout.createSequentialGroup()
                        .addComponent(jB_mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jB_mesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jB_mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jP_MesasLayout.setVerticalGroup(
            jP_MesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_MesasLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jP_MesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_mesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_MesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_mesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_mesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_mesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Mesas", jP_Mesas);

        jPanel7.setPreferredSize(new java.awt.Dimension(570, 200));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jButton1.setText("Cancelar");

        jButton2.setText("Generar Ticket");

        jPanel10.setPreferredSize(new java.awt.Dimension(570, 200));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel10);

        javax.swing.GroupLayout jP_FacturacionLayout = new javax.swing.GroupLayout(jP_Facturacion);
        jP_Facturacion.setLayout(jP_FacturacionLayout);
        jP_FacturacionLayout.setHorizontalGroup(
            jP_FacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_FacturacionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jP_FacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jP_FacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_FacturacionLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jP_FacturacionLayout.setVerticalGroup(
            jP_FacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_FacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_FacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_FacturacionLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jP_FacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_FacturacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Facturación", jP_Facturacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_mesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_mesa1ActionPerformed

    private void jB_mesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mesa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_mesa2ActionPerformed

    private void jB_mesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mesa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_mesa3ActionPerformed

    private void jB_mesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mesa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_mesa4ActionPerformed

    private void jB_mesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mesa5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_mesa5ActionPerformed

    private void jB_mesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mesa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_mesa6ActionPerformed
    // AL CERRAR LA VENTANA CERRAMOS LA CONEXIÓN
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            con.close();
            System.out.println("Desconectados de Academia");
        } catch (SQLException sqe) {
            System.out.println(
                    "No se pudo desconectar " + sqe.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    /* Pintar los usuarios */
    public void pintar_camareros() {
        jP_seleccionar_camareros.setLayout(new FlowLayout());
        try {
            // CREAR OBJETO STATEMENT
            Statement st = con.createStatement();
            // EJECUTAR SQL
            ResultSet rs = st.executeQuery("SELECT Nombre, ID_Camarero FROM CAMAREROS");
            while (rs.next()) {
                String nombre_camarero = rs.getString("Nombre");
                String id_camarero = rs.getString("ID_Camarero");
                String url_camarero = "/img/" + id_camarero + ".jpg";
                Color colorFondo = new Color(147, 147, 147);
                Color colorHover = new Color(200, 200, 200);
                JButton btn_camarero = pintar_tarjetas(nombre_camarero, url_camarero, colorFondo, colorHover, 150, 150);
                jP_seleccionar_camareros.add(btn_camarero);
            }

        } catch (SQLException sqe) {
            System.out.println("Error siguiente: " + sqe.getMessage());
        }

    }

    public JButton pintar_tarjetas(String nombre, String url, Color colorFondo, Color colorHover, int ancho, int alto) {
        JButton btn_tarjeta = new JButton(nombre);
        // ESTILOS
        btn_tarjeta.setSize(ancho, alto);
        btn_tarjeta.setContentAreaFilled(false);
        btn_tarjeta.setIcon(setIcono(url, btn_tarjeta));
        btn_tarjeta.setIconTextGap(5);
        btn_tarjeta.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_tarjeta.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_tarjeta.setOpaque(true);
        btn_tarjeta.setBackground(colorFondo);
        // ESTILOS HOVER Y CLICK
        btn_tarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                super.mouseEntered(evt);
                btn_tarjeta.setBackground(colorHover);
            }

            public void mouseExited(MouseEvent evt) {
                super.mouseExited(evt);
                btn_tarjeta.setBackground(colorFondo);
            }
        });
        return btn_tarjeta;
    }

    /* Renderizado automático deo tamaño de las imágenes de los botones */
    public Icon setIcono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_mesa1;
    private javax.swing.JButton jB_mesa2;
    private javax.swing.JButton jB_mesa3;
    private javax.swing.JButton jB_mesa4;
    private javax.swing.JButton jB_mesa5;
    private javax.swing.JButton jB_mesa6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jP_Facturacion;
    private javax.swing.JPanel jP_Mesas;
    private javax.swing.JPanel jP_camareros;
    private javax.swing.JPanel jP_seleccionar_camareros;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
